import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/homepage">Homepage</Link>
        </li>
        <li>
          <Link to="/addupcomingshows">AddUpcomingShows</Link>
        </li>
        <li>
          <Link to="/aboutus">Aboutus</Link>
        </li>
        <li>
          <Link to="/addnewmember">AddNewMember</Link>
        </li>
        <li>
          <Link to="/vogliveseries">VOGLiveSeries</Link>
        </li>
        <li>
          <Link to="/addvogliveseries">AddVOGLiveSeries</Link>
        </li>
        <li>
          <Link to="/tvshows">TVShows</Link>
        </li>
        <li>
          <Link to="/addtvshows">AddTVShows</Link>
        </li>
        <li>
          <Link to="/fmstation">FMStation</Link>
        </li>
        <li>
          <Link to="/addfmstationone">AddFMStationOne</Link>
        </li>
        <li>
          <Link to="/royalnews">RoyalNews</Link>
        </li>
        <li>
          <Link to="/addfmstation">AddFMStation</Link>
        </li>
        <li>
          <Link to="/contactus">ContactUs</Link>
        </li>
        <li>
          <Link to="/addpreviousshows">AddPreviousShows</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
